language: nix

before_script:
  - mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
  - nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
  - nix-channel --update
  - export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
  - nix-shell '<home-manager>' -A install
  - mkdir -p ~/.config/nixpkgs
  - ln *.nix ~/.config/nixpkgs

script:
  - home-manager switch

notifications:
  email:
    on_failure: always
